import React from "react";

const ProductSection = () => {
  return (
    <section className="px-6 py-12 max-w-4xl mx-auto text-white" id="products">
      <h2 className="text-3xl font-bold mb-6 text-cyan-400">Our Product</h2>

      <p className="mb-4">
        <strong>e-Spark is not just another EV charging solution</strong> — it’s a digitally-powered infrastructure model built for the future of energy, finance, and mobility.
      </p>

      <p className="mb-4">
        We combine <strong>EV chargers</strong> with <strong>battery energy storage systems (BESS)</strong> in a dual-layer model. Each asset is tokenized on-chain as a unique <strong>NFT</strong>, enabling real-time tracking, lifecycle management, and project assignment.
      </p>

      <p className="mb-4">
        Each deployment unit (project) is governed by a smart contract that issues <strong>commercial tokens</strong> for investors. These tokens are tied to automated revenue streams:
      </p>

      <ul className="list-disc list-inside mb-6 ml-4">
        <li><strong>Charging revenue</strong> from EV users</li>
        <li><strong>Energy arbitrage</strong> — storing energy at low cost, selling when prices spike</li>
        <li><strong>Carbon credits</strong> — earned through emissions displacement and clean energy delivery</li>
      </ul>

      <h3 className="text-2xl font-semibold mb-3 text-cyan-300">Smart Grid. Smart Returns.</h3>

      <p className="mb-4">
        Our batteries perform <strong>energy arbitrage</strong>, reducing stress on the grid and enhancing infrastructure ROI. This strengthens energy resilience and unlocks sustainable income.
      </p>

      <p className="mb-4">
        <strong>Carbon credits</strong> are generated by verified reductions in emissions when clean energy replaces fossil sources. These credits are tokenized and monetized through market mechanisms.
      </p>

      <h3 className="text-2xl font-semibold mb-3 text-cyan-300">Tokenomics with Purpose</h3>

      <p className="mb-4">
        Each project token includes three profit layers:
      </p>

      <ol className="list-decimal list-inside mb-6 ml-4">
        <li><strong>4% fixed yield</strong> — infrastructure-backed</li>
        <li><strong>0–2% pool-based yield</strong> — tied to the total network performance</li>
        <li><strong>0–2% local project yield</strong> — based on charger usage, arbitrage and carbon credit performance</li>
      </ol>

      <h3 className="text-2xl font-semibold mb-3 text-cyan-300">Built for the Long Haul</h3>

      <p className="mb-4">
        Our model is designed for real, sustainable value — not short-term speculation. By connecting infrastructure investment with transparent Web3 economics, e-Spark scales EV charging intelligently and responsibly.
      </p>

      <p className="font-bold">
        This is the product of tomorrow — grounded in real-world deployment, optimized for long-term impact.
      </p>
    </section>
  );
};

export default ProductSection;
